# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'copyPrototype.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon, QPixmap
from tkinter import Tk
from PIL import ImageGrab



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.copyNow = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press_it())
        self.copyNow.setGeometry(QtCore.QRect(60, 430, 131, 51))
        self.copyNow.setObjectName("copyNow")
        self.copyLabel = QtWidgets.QLabel(self.centralwidget)
        self.copyLabel.setGeometry(QtCore.QRect(40, 180, 251, 171))
        self.copyLabel.setText("")
        self.copyLabel.setObjectName("copyLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def press_it(self):
        try:
            copy = Tk().clipboard_get()
        except:
            copy = ImageGrab.grabclipboard()
        if isinstance(copy,str):
            self.copyLabel.setText(copy)
        else:
            copy.save('paste.png', 'PNG')
            pixmap = QPixmap('paste.png')
            self.copyLabel.setPixmap(pixmap)


           # self.resize(pixmap.width(),pixmap.height())



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.copyNow.setText(_translate("MainWindow", "grab copy"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
